{
 "title": "Booster",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "ReadModels methods total count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "booster_readmodel_total_count{}",
     "legendFormat": "{{methodName}}"
    }
   ]
  },
  {
   "title": "Methods count (Rate per 2000s)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 10, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(booster_methods_total_count{}[2000s])",
     "legendFormat": "{{methodName}}"
    }
   ]
  },
  {
   "title": "Events Processor total count (rate/5000)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(booster_events_total_count{}[5000s])",
     "legendFormat": "{{eventName}}"
    }
   ]
  },
  {
   "title": "Events Processor total count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 9 },
   "targets": [
    { "expr": "booster_events_total_count{}", "legendFormat": "{{eventName}}" }
   ]
  },
  {
   "title": "Methods total count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 9 },
   "targets": [
    { "expr": "booster_methods_total_count{}", "legendFormat": "{{methodName}}" }
   ]
  },
  {
   "title": "Methods duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "booster_methods_duration_ms_count{}",
     "legendFormat": "{{methodName}}"
    }
   ]
  }
 ]
}